version: '3.8'

services:
  webapp:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - CATALINA_OPTS=-Xms512m -Xmx1024m
    restart: always
    networks:
      - java-app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: javaapp
      MYSQL_USER: javaapp
      MYSQL_PASSWORD: javaapp123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - java-app-network

networks:
  java-app-network:
    driver: bridge

volumes:
  mysql-data:
